# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPID', models.CharField(default=False, max_length=20)),
                ('fullName', models.CharField(blank=True, max_length=40)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('isCheckin', models.BooleanField(default=False)),
                ('shiftLength', models.CharField(blank=True, max_length=20)),
                ('startTime', models.CharField(blank=True, max_length=10)),
                ('endTime', models.CharField(blank=True, max_length=10)),
                ('isNoShow', models.BooleanField(default=True)),
                ('isCheckout', models.BooleanField(default=False)),
                ('timeCheckin', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('startTime', 'firstName'),
            },
        ),
    ]
