# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='shiftLength',
            new_name='blockTime',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='timeCheckin',
            new_name='checkinTime',
        ),
    ]
