# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20180619_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='checkinTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
