# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20180619_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='shiftLength',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='isNoShow',
            field=models.BooleanField(),
        ),
    ]
